### ISSUE TITLE
Error scikit-learn versions of the pretrained classifier and installed version do not match 

### ISSUE THREAD

**Issue by aimirza** [wasade/q2-greengenes2#26]
I am trying to run the retrained classifier [2022.10.backbone.v4.nb.sklearn-1.4.2.qza](http://ftp.microbio.me/greengenes_release/current/sklearn-1.4.2-compatible-nb-classifiers/) but I get the error that my scikit-learn version does not match the scikit-learn version used to create the classifier. How do I solve this issue? I am using qiime2 version 2024.2. The full error log is below

```
Traceback (most recent call last):
  File "/home/amirza/miniforge3/envs/qiime2-amplicon-2024.2/lib/python3.8/site-packages/q2cli/commands.py", line 520, in __call__
    results = self._execute_action(
  File "/home/amirza/miniforge3/envs/qiime2-amplicon-2024.2/lib/python3.8/site-packages/q2cli/commands.py", line 581, in _execute_action
    results = action(**arguments)
  File "<decorator-gen-314>", line 2, in classify_sklearn
  File "/home/amirza/miniforge3/envs/qiime2-amplicon-2024.2/lib/python3.8/site-packages/qiime2/sdk/action.py", line 339, in bound_callable
    self.signature.transform_and_add_callable_args_to_prov(
  File "/home/amirza/miniforge3/envs/qiime2-amplicon-2024.2/lib/python3.8/site-packages/qiime2/core/type/signature.py", line 395, in transform_and_add_callable_args_to_prov
    self._transform_and_add_input_to_prov(
  File "/home/amirza/miniforge3/envs/qiime2-amplicon-2024.2/lib/python3.8/site-packages/qiime2/core/type/signature.py", line 428, in _transform_and_add_input_to_prov
    transformed_input = _input._view(spec.view_type, recorder)
  File "/home/amirza/miniforge3/envs/qiime2-amplicon-2024.2/lib/python3.8/site-packages/qiime2/sdk/result.py", line 406, in _view
    result = transformation(self._archiver.data_dir)
  File "/home/amirza/miniforge3/envs/qiime2-amplicon-2024.2/lib/python3.8/site-packages/qiime2/core/transform.py", line 70, in transformation
    new_view = transformer(view)
  File "/home/amirza/miniforge3/envs/qiime2-amplicon-2024.2/lib/python3.8/site-packages/q2_feature_classifier/_taxonomic_classifier.py", line 59, in _1
    raise ValueError('The scikit-learn version (%s) used to generate this'
ValueError: The scikit-learn version (1.4.2) used to generate this artifact does not match the current version of scikit-learn installed (0.24.1). Please retrain your classifier for your current deployment to prevent data-corruption errors.

Plugin error from feature-classifier:

  The scikit-learn version (1.4.2) used to generate this artifact does not match the current version of scikit-learn installed (0.24.1). Please retrain your classifier for your current deployment to prevent data-corruption errors.
```

**Comment by wasade** [comment]
Hi @aimirza,

I primarily monitor the QIIME 2 forum for QIIME 2 related questions. I believe sklearn 1.4.2 is used in QIIME 2 2024.5 and is not compatible with prior versions.

If this is still an issue, please open a thread on the QIIME 2 Forum and tag it as greengenes2

Best,
Daniel
